### ISSUE TITLE
Minimising Mame romset

### ISSUE THREAD

**Issue by Cissoubaka** [paradadf/recaltools#1]
Is it possible to add to the excel file a new tab for comparing the fba and mame list, to remove all the dupe between fba and mame,
if a game is present in fba list and mame list, only keep the one in fba list,
If a game is only present in fba, keep it
If a game is present in mame list, keep it,

By doing this, we'll have a mame reduced list to the minimum I think (whatever the choose of the filter)

**Comment by paradadf** [comment]
I'm willing to add such functionality, but by the current lack of help from the community side to fill up the compatibility lists, it would be no so useful. mame2003 list is a joke at this point.

I had thought about this, but my approach would be a bit more complex. I would let the user decide which core should be preferred in case of a similar status. Because, for example, if you filter **OK** and **Has (minor) issues** roms, but for a specific game mame has the **OK** and fba_libretro the **Has (minor) issues** status, mame should be chosen (if the user wants that!).

**Comment by Cissoubaka** [comment]
Indeed, but maybe you could use this file (only for rpi3) [https://docs.google.com/spreadsheets/d/1F5tBguhRxpj1AQcnDWF6AVSx4av_Gm3cDQedQB7IECk/edit#gid=2031763640](BestArcade4RecalBox)

**Comment by paradadf** [comment]
That wouldn't be a good idea. That list is outdated and I need a certain format. If I get bored and find some time, I will work on this... but if I don't see any help of the community, I won't be motivated to do so.
I alone tested all roms you see on the fba_libretro compatibility list. Those are over 2600 roms. The lists were published 17 days ago... only 5 roms have been added since to the mame list. So dissapointing :(

**Comment by Cissoubaka** [comment]
if you can wait i could help you filling the mame2003 list during christmas holidays

**Comment by paradadf** [comment]
I won't be testing a single rom for months :P. But as I said before, if I see the list filling up, that will motivate me to keep working on the tools. My recommendation would be to use a RPi2 if you have it, and copy the **OK** directly to the RPi3 colummn. That way it is less work for everyone.

**Comment by Cissoubaka** [comment]
Started to fill the compatibility list from the bottom 
using a Rpi2

**Comment by paradadf** [comment]
Done! ;)
I hope the community slowly responds to everything we have done for them.
