### ISSUE TITLE
problems Correct use of your "Automatic Gamelists Filter.xlsx"

### ISSUE THREAD

**Issue by giallone1970** [paradadf/recaltools#4]
Hello,
i tried to use your "Automatic Gamelists Filter.xlsx" but for some reasons, i'm not able to obtain a result at all

- if i open the xlsx with latest version of libreoffice calc then, when i paste from the mame2003 compatibility list, it just stucks forever in pasting..
- if i "import your file on google documents then i paste there, i get errors on formulas and lose parts of it (no way i can filter results in any way)

Can you suggest what program we have to use (hope not only MS excel) or particular things to do to obtain a succesful paste?

I use windows10 currently, thank you! =)

**Comment by paradadf** [comment]
Hi!

To be honest, I created it wirh Excel because that's the software.
I know the table wont work on google sheets (at lease the online version, not sure if there is another), because it uses defined ranges (formulas) with aren't compatible with gdocs. Actually, a couple of weeks ago the sheet had formulas without names and gdocs was able to handle it but it was SUUUUUPER SLOW! It needed a couple of minutes for all calculations and that wasn't really practical. So I removed the formulas to have better readability and easier development.
I know for sure that Excel online can handle it as well and pretty fast also (one more reason no to use google sheets), so that's something you can try.
It is already late today but tomorrow I can try to find some comprible free software to use it with and recommend it. But that's the point, the named formulas aren't compatible with all excel-like softwares. Google sheets allows defined ranges, but no defined formulas.

**Comment by giallone1970** [comment]
Hello,
thank you for prompt answers, don't worry, i can use online excel =)
also i found a solution somewhat:
if i do a copy of the compatibility sheet, download and convert in .ODS
format (open office sheet format) i can then copy paste in your file
without big problems. A bit slow but works and i can do choices and all
formulas seems to work (i was able to save my list at least ^^)
thank to you again for the excellent tool!



2016-12-20 0:40 GMT+01:00 paradadf <notifications@github.com>:

**Comment by paradadf** [comment]
Good to know that the formulas work on OpenOffice. I suppose, they will work on almost any spreadsheet software, as long as you use the offline version. And as I said before, Excel Online works too ;)
