### ISSUE TITLE
Wrong path  ?

### ISSUE THREAD

**Issue by Laddyacris** [paradadf/recaltools#5]
Hello @paradadf 
I tried your batch fastsorter.bat and It's not work on windows 10.

I modified path for folder and it's ok now.

this path `".\%system%\ doesn't work on windows"`

I modified path for folder and it's ok now on my computer
```
:createFolder
rem Create the selected folder
md "D:\%system%\%destFolder%"

rem Look inside the gamelist and copy the roms to the destination folder
if not exist "%gamelist%.txt" echo The file %gamelist%.txt is missing! & echo. & pause & goto:eof
title fastsorter ver. %releaseDate% - Sorting roms in progress...
for /f "delims=" %%a in ('type "%gamelist%.txt"') do (
	if exist "D:\%system%\%%a" (
		copy "D:\%system%\%%a" "D:\%system%\%destFolder%\%%~nxa" >nul | echo %%a
	) else (
		echo.
		echo %%a missing & echo.
		)
)
```

**Comment by paradadf** [comment]
Hi @Laddyacris,

I believe the problem is that I erased the instructions on where to place the files exactly and it's a little confusing right now, sorry about that.
The old instructions with pictures are here: http://imgur.com/a/iyxKF
You can see the structure there. I plan to make it very clear, just haven't had the time to do it.

Right now it works only if your folders "fba_libretro" or "mame" are next to fastsorter.bat and the source file, either fastsorter.txt or one of the longer names, are also on the same root folder.

%system% ist just the name of the variable, either fba_libretro or mame.

I leave the issue open until I make it bullet proof. If you still have problems, just let me know.

**Comment by paradadf** [comment]
@Laddyacris, it should be much easier and clearer now, I hope!
